name: kube-downscaler
apiVersion: v1
version: 0.1.1
appVersion: 0.5.1
description:  A Helm chart for kube-downscaler
keywords:
  - k8s pods scheduler
  - scheduled lifecycle
sources:
  - https://codeberg.org/hjacobs/kube-downscaler
