{{- $dot := . -}}
{{- range $k, $v := .Values.schedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" $dot }}-{{ $k | lower }}
  labels:
    {{- include "cronjob.labels" $dot | nindent 4 }}
spec:
  schedule: {{ $v.cron | quote }}
  concurrencyPolicy: {{ $dot.Values.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ $dot.Values.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ $dot.Values.failedJobsHistoryLimit | default 1 }}
  startingDeadlineSeconds: {{ $v.startingDeadlineSeconds | default 600 }}
  jobTemplate:
    spec:
      backoffLimit: {{ $dot.Values.backoffLimit | default 3 }}
      template:
        spec:
          {{- with $dot.Values.imagePullSecret }}
          imagePullSecrets:
            - name: {{ . }}
          {{- end }}
          serviceAccountName: {{ include "cronjob.serviceAccountName" $dot }}
          securityContext:
            {{- toYaml $dot.Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ $dot.Values.restartPolicy | default "Never" }}
          containers:
            - name: worker
              image: "{{ $dot.Values.image.repository }}:{{ $dot.Values.image.tag | default $dot.Chart.AppVersion }}"
              imagePullPolicy: {{ $dot.Values.image.pullPolicy }}
              env:
                - name: "EXCHANGE"
                  value: {{ $k | quote }}
                {{- with $dot.Values.env }}
                  {{- toYaml . | nindent 16 }}
                {{- end }}
              securityContext:
                {{- toYaml $dot.Values.securityContext | nindent 16 }}
              volumeMounts:
                - name: config
                  readOnly: true
                  mountPath: /config/default.yaml
                  subPath: "default.yaml"
              resources:
                {{- toYaml $dot.Values.resources | nindent 16 }}
          volumes:
            - name: config
              secret:
                secretName: {{ $dot.Values.config.name | default "cronjobs" }}
                items:
                  - key: {{ $dot.Values.config.key | default "default.yaml" }}
                    path: default.yaml
          {{- with $dot.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $dot.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $dot.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
