# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/quotes-strategies

  config:
    secret: "quotes-strategies"

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false
