# -- schedule for workflow
schedule: {}
  # PA:
  #   cron: "15 18 * * 1-5"
  #   startingDeadlineSeconds: 600
  # BR:
  #   cron: "15 18 * * 1-5"
  #   startingDeadlineSeconds: 600

# -- timezone is the timezone to use for the schedule
timezone: Europe/Paris
# -- concurrencyPolicy is the policy for handling concurrent jobs
concurrencyPolicy: Forbid
# -- successfulJobsHistoryLimit is the number of successful jobs to keep
successfulJobsHistoryLimit: 1
# -- failedJobsHistoryLimit is the number of failed jobs to keep
failedJobsHistoryLimit: 1
# -- restartPolicy is the policy for handling job failures
restartPolicy: "Never"
# -- backoffLimit is the number of retries before considering the job failed
backoffLimit: 3
# -- podGC is the policy for handling pod garbage collection
podGC: OnWorkflowSuccess

# -- imagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this Chart.
imagePullSecret: regcred 
# -- nameOverride is an optional string to substitute for the full names of resources
nameOverride: ""
# -- fullnameOverride is an optional string to substitute for the full names of resources
fullnameOverride: ""
# -- annotations is an optional map of annotations to add to the pod
annotations: {}

# -- serviceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
  # -- Rules/RoleBinding to add to the ServiceAccount
  rules: []
    # - apiGroups: [""]
    #   resources: ["pods"]
    #   verbs: ["get", "list", "watch"]
    # - apiGroups: [""]
    #   resources: ["pods/log"]
    #   verbs: ["get"]

# -- securityGroups is an optional configuration for AWS security groups
securityGroups:
  enabled: false
  # -- serviceAccountSelector is an optional matchLabels to select the service account
  serviceAccountSelector: {}
  # -- rules is an optional list of rules to add to the security group
  rules: []
    # - "sg-1234567890abcdef0"

# -- templates is a map of templates to run
templates: {}
  # splits-template:
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-split-update:0.3.0
  #     pullPolicy: IfNotPresent
  #     command: ["/bin/go"]
  #     args: ["/config/default.yaml"]
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #       - name: DATABASE_DEBUG
  #         value: "true"
  #     volumeMounts:
  #       - name: splits-config
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #     resources:
  #       limits:
  #         cpu: 30m
  #         memory: 72Mi
  #       requests:
  #         cpu: 30m
  #         memory: 72Mi
  #   volumes:
  #     - name: splits-config
  #       secret:
  #         secretName: workers
  #         items:
  #           - key: splits
  #             path: default.yaml
  # main:
  #   dag:
  #     tasks:
  #       - name: splits
  #         template: splits-template

# -- securityContext is an optional security context to add to the container
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector:
  kubernetes.io/os: linux

# -- tolerations is an optional list of tolerations to add to the container
tolerations: []

# -- affinity is an optional affinity to add to the container
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - arm64
