# Default values for workflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: {}
  # PA:
  #   cron: "30 1-8 * * 2-6"
  #   startingDeadlineSeconds: 600
  # BR:
  #   cron: "30 1-8 * * 2-6"
  #   startingDeadlineSeconds: 600

timezone: Europe/Paris
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
restartPolicy: "Never"
backoffLimit: 3

imagePullSecret: regcred 
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# First Job must have main name
templates: {}
  # - name: splits-template
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-instrument-splits:1.0.2
  #     pullPolicy: IfNotPresent
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #     volumeMounts:
  #       - name: splits
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #     resources:
  #       limits:
  #         cpu: 30m
  #         memory: 72Mi
  #       requests:
  #         cpu: 30m
  #         memory: 72Mi
  # - name: quotes-template
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-instrument-quotes:1.0.2
  #     pullPolicy: IfNotPresent
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #     volumeMounts:
  #       - name: quotes
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #     resources:
  #       limits:
  #         cpu: 30m
  #         memory: 72Mi
  #       requests:
  #         cpu: 30m
  #         memory: 72Mi
  # - name: dividends-template
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-instrument-dividends:1.0.2
  #     pullPolicy: IfNotPresent
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #     volumeMounts:
  #       - name: dividends
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #     resources:
  #       limits:
  #         cpu: 30m
  #         memory: 72Mi
  #       requests:
  #         cpu: 30m
  #         memory: 72Mi
  # - name: stats-template
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-instrument-stats:1.0.2
  #     pullPolicy: IfNotPresent
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #     volumeMounts:
  #       - name: stats
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #     resources:
  #       limits:
  #         cpu: 100m
  #         memory: 72Mi
  #       requests:
  #         cpu: 100m
  #         memory: 72Mi
  # - name: meilisearch-template
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-instrument-meilisearch:1.0.2
  #     pullPolicy: IfNotPresent
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #     volumeMounts:
  #       - name: meilisearch
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #     resources:
  #       limits:
  #         cpu: 20m
  #         memory: 56Mi
  #       requests:
  #         cpu: 20m
  #         memory: 56Mi
  # - name: main
  #   dag:
  #     tasks:
  #       - name: splits
  #         template: splits-template
  #       - name: quotes
  #         depends: "splits"
  #         template: quotes-template
  #       - name: dividends
  #         depends: "splits"
  #         template: dividends-template
  #       - name: stats
  #         depends: "quotes && dividends"
  #         template: stats-template
  #       - name: meilisearch
  #         depends: "stats"
  #         template: meilisearch-template

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

env:
  - name: DATABASE_DEBUG
    value: "true"
  # - name: API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: eod-api
  #       key: value

volumes: {}
  # - name: splits-config
  #   secret:
  #     secretName: microservices
  #     items:
  #       - key: splits
  #         path: default.yaml
  # - name: quotes-config
  #   secret:
  #     secretName: microservices
  #     items:
  #       - key: quotes
  #         path: default.yaml
  # - name: dividends-config
  #   secret:
  #     secretName: microservices
  #     items:
  #       - key: dividends
  #         path: default.yaml
  # - name: stats-config
  #   secret:
  #     secretName: microservices
  #     items:
  #       - key: stats
  #         path: default.yaml
  # - name: meilisearch-config
  #   secret:
  #     secretName: microservices
  #     items:
  #       - key: meilisearch
  #         path: default.yaml
  # - name: nats
  #   secret:
  #     secretName: "natscred"
  #     items:
  #       - key: microservices.creds
  #         path: microservices.creds

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
  k8s.scaleway.com/pool-name: default

tolerations: []

affinity: {}
