# Default values for workflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: {}
  # PA:
  #   cron: "15 18 * * 1-5"
  #   startingDeadlineSeconds: 600
  # BR:
  #   cron: "15 18 * * 1-5"
  #   startingDeadlineSeconds: 600

timezone: Europe/Paris
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
restartPolicy: "Never"
backoffLimit: 3
podGC: OnWorkflowSuccess

imagePullSecret: regcred 
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# First Job must have main name
templates:
  # - name: splits-template
  #   container:
  #     image: rg.nl-ams.scw.cloud/arktos-fund/worker-split-update:0.3.0
  #     pullPolicy: IfNotPresent
  #     command: ["/bin/go"]
  #     args: ["/config/default.yaml"]
  #     env:
  #       - name: "EXCHANGE"
  #         value: "{{workflow.parameters.exchange}}"
  #       - name: DATABASE_DEBUG
  #         value: "true"
  #     volumeMounts:
  #       - name: splits-config
  #         readOnly: true
  #         mountPath: /config/default.yaml
  #         subPath: "default.yaml"
  #       - name: nats
  #         readOnly: true
  #         mountPath: microservices.creds
  #         subPath: microservices.creds
  #     resources:
  #       limits:
  #         cpu: 30m
  #         memory: 72Mi
  #       requests:
  #         cpu: 30m
  #         memory: 72Mi
  #   volumes:
  #     - name: splits-config
  #       secret:
  #         secretName: workers
  #         items:
  #           - key: splits
  #             path: default.yaml
  #     - name: nats
  #       secret:
  #         secretName: "natscred"
  #         items:
  #           - key: microservices.creds
  #             path: microservices.creds
  # - name: main
  #   dag:
  #     tasks:
  #       - name: splits
  #         template: splits-template

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
  k8s.scaleway.com/pool-name: default

tolerations: []

affinity: {}
