{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workflow.serviceAccountName" . }}
  labels:
    {{- include "workflow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "workflow.serviceAccountName" . }}-executor
rules:
  - apiGroups:
      - argoproj.io/v1alpha1
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "workflow.serviceAccountName" . }}-executor
subjects:
  - kind: ServiceAccount
    name: {{ include "workflow.serviceAccountName" . }}
    apiGroup: "argoproj.io"
roleRef:
  kind: Role
  name: {{ include "workflow.serviceAccountName" . }}-executor
  apiGroup: rbac.authorization.k8s.io
{{- end }}
