{{- if and .Values.serviceAccount.create (gt (.Values.serviceAccount.rules | len) 0) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r-{{ include "workflow.serviceAccountName" . }}
  labels:
    {{- include "workflow.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.serviceAccount.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-{{ include "workflow.serviceAccountName" . }}
  labels:
    {{- include "workflow.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "workflow.serviceAccountName" . }}
roleRef:
  kind: Role
  name: r-{{ include "workflow.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
