apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "workflow.fullname" . }}-template
  labels:
    {{- include "workflow.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceAccountName: {{ include "workflow.serviceAccountName" . }}
  templates:
    {{- toYaml .Values.templates | nindent 4 }}
