apiVersion: v2
name: cronjob
description: A Helm chart Cronjob for Kubernetes
type: application
version: 0.1.9
appVersion: "0.0.1"
home: https://github.com/hartza-capital/helm-charts
keywords:
  - hartza-capital
  - aws
maintainers:
  - name: perriea
    email: aperrier@hartza.capital
