# Default values for microservice.

imports:
  quotes:
    north-america:
      enabled: true
      schedule: "50 23 * * 1-5"
      exchanges:
        - NASDAQ
        - NYSE
        - TO
        
      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi 

    south-europe:
      enabled: true
      schedule: "30 17 * * 1-5"
      exchanges: 
        - LS
        - MI
        - MC

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi  

    central-europe:
      enabled: true
      schedule: "0 17 * * 1-5"
      exchanges:
        - PA
        - BR
        - AS
        - F
           
      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

    north-europe:
      enabled: true
      schedule: "0 18 * * 1-5"
      exchanges:
        - LSE

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

    central-asia:
      enabled: true
      schedule: "30 10 * * 1-5"
      exchanges: 
        - SHE
        - SHG
        - HK

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

    south-asia:
      enabled: true
      schedule: "0 11 * * 1-5"
      exchanges:
        - SG

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux