# Default values for microservice.

imports:
  currency_quotes:
    schedule: 30 1 * 2-6"

    resources:
      limits:
        cpu: 80m
        memory: 96Mi
      requests:
        cpu: 80m
        memory: 96Mi  

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux