# Default values for microservice.

imports:
  companies:
    north-america:
      enabled: true
      schedule: "0 16 * * 1"
      exchanges:
        - NASDAQ
        - NYSE
        - TO
        
      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi 

    south-europe:
      enabled: true
      schedule: "0 10 * * 2"
      exchanges: 
        - LS
        - MI
        - MC

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi  

    central-europe:
      enabled: true
      schedule: "0 12 * * 3"
      exchanges:
        - PA
        - BR
        - AS
        - F
           
      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

    north-europe:
      enabled: true
      schedule: "0 14 * * 4"
      exchanges:
        - LSE

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

    central-asia:
      enabled: true
      schedule: "0 4 * * 5"
      exchanges: 
        - SHE
        - SHG
        - HK

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

    south-asia:
      enabled: true
      schedule: "0 6 * * 6"
      exchanges:
        - SG

      resources:
        limits:
          cpu: 80m
          memory: 96Mi
        requests:
          cpu: 80m
          memory: 96Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux