apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
data:
  ibgateway.vmoptions: |-
    -Xms{{ .Values.jvm.Xms | default "2G" }}
    -Xmx{{ .Values.jvm.Xmx | default "2G" }}
    -XX:+Use{{ .Values.jvm.GCollector | default "G1GC" }}
    -XX:MaxGCPauseMillis={{ .Values.jvm.XX.MaxGCPauseMillis | default "200" }}
    -XX:ParallelGCThreads={{ .Values.jvm.XX.ParallelGCThreads | default "20" }}
    -XX:ConcGCThreads={{ .Values.jvm.XX.ConcGCThreads | default "5" }}
    -XX:InitiatingHeapOccupancyPercent={{ .Values.jvm.XX.InitiatingHeapOccupancyPercent | default "70" }}
    -Dinstaller.uuid={{ required "UUID JVM requirement" .Values.jvm.installer.uuid }}
    -DvmOptionsPath=/home/trader/Jts/ibgateway/{{ include "ibkr-gateway.version" . }}/ibgateway.vmoptions
    -Dsun.awt.nopixfmt=true
    -Dsun.java2d.noddraw=true
    -Dswing.boldMetal=false
    -Dsun.locale.formatasdefault=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}-supervisord
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
data:
  supervisord.conf: |-
    [supervisord]
    nodaemon=false
    loglevel=info
    user=trader
    logfile=/dev/stdout
    logfile_maxbytes=0

{{- range .Values.config.workers }}
    [program:{{ .name }}]
    command={{ .command }}
    directory={{ .directory | default "/home/trader/app" }}
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    redirect_stderr=true
    autostart=true
    autorestart=true
    startretries={{ .startretries | default "3" }}
    stopsignal={{ .stopsignal | default "QUIT" }}
{{- end }}

    [supervisorctl]
