apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}-nginx
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    load_module /usr/lib/nginx/modules/ngx_stream_module.so;
    worker_processes auto;
    events { }
    stream {
      server {
        listen 8888;
        proxy_pass 127.0.0.1:4001;
      }
    }