apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "ibkr-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.gateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ibkr-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- if ne .Values.serviceAccount.create true }}
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "ibkr-gateway.serviceAccountName" . | default "default" }}
      securityContext:
        {{- toYaml .Values.gateway.podSecurityContext | nindent 8 }}
      containers:
        - name: gateway
          securityContext:
            {{- toYaml .Values.gateway.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          {{- with .Values.gateway.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: vnc
              containerPort: 5900
              protocol: TCP
            - name: socket
              containerPort: {{ if .Values.gateway.config.live }}4001{{ else }}4002{{ end }}
              protocol: TCP
          {{- if .Values.gateway.config.proxy }}
            - name: tunnel-socket
              containerPort: 5000
              protocol: TCP
          {{- end }}
          {{- if eq .Values.gateway.debug false }}
          livenessProbe:
            tcpSocket:  
              port: {{ if .Values.gateway.config.live }}4001{{ else }}4002{{ end }}
            initialDelaySeconds: 500
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:  
              port: {{ if .Values.gateway.config.live }}4001{{ else }}4002{{ end }}
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
          volumeMounts:
            - name: {{ include "ibkr-gateway.fullname" . }}-config
              mountPath: /opt/ibc/config.ini
              subPath: config.ini
            - name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
              mountPath: /home/trader/Jts/ibgateway/{{ include "ibkr-gateway.version" . }}/ibgateway.vmoptions
              subPath: ibgateway.vmoptions
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
        {{- range .Values.sidecars.containers }}
        - name: {{ .name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ .image | quote }}
          imagePullPolicy: {{ .imagePullPolicy }}
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          volumeMounts:
            - name: ibkr-{{ .name }}-worker
              mountPath: /home/noroot/config.yaml
              subPath: config.yaml
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: {{ include "ibkr-gateway.fullname" . }}-config
          secret:
            secretName: {{ .Values.gateway.config.credentials | default "credentials" }}
            items:
              - key: config.ini
                path: config.ini
        - name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
          configMap:
            name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
        {{- range .Values.sidecars.containers }}
        - name: ibkr-{{ .name }}-worker
          secret:
            secretName: ibkr-workers
            items:
              - key: {{ .name }}
                path: config.yaml
        {{- end }}
        {{- with .Values.sidecars.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}