{{- $dot := . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "ibkr-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ibkr-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- if ne .Values.serviceAccount.create true }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "ibkr-gateway.serviceAccountName" . | default "default" }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: vnc
              containerPort: 5900
              protocol: TCP
            - name: socket
              containerPort: {{ if .Values.config.live }}4001{{ else }}4002{{ end }}
              protocol: TCP
          {{- if .Values.config.proxy }}
            - name: tunnel-socket
              containerPort: 5000
              protocol: TCP
          {{- end }}
          {{- if eq .Values.debug false }}
          livenessProbe:
            tcpSocket:  
              port: {{ if .Values.config.live }}4001{{ else }}4002{{ end }}
            initialDelaySeconds: 500
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:  
              port: {{ if .Values.config.live }}4001{{ else }}4002{{ end }}
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
          volumeMounts:
            - name: {{ include "ibkr-gateway.fullname" . }}-config
              mountPath: /opt/ibc/config.ini
              subPath: config.ini
            - name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
              mountPath: /home/trader/Jts/ibgateway/{{ include "ibkr-gateway.version" . }}/ibgateway.vmoptions
              subPath: ibgateway.vmoptions
            - name: {{ include "ibkr-gateway.fullname" . }}-supervisord
              mountPath: /etc/supervisor/supervisord.conf
              subPath: supervisord.conf
            {{- range .Values.config.workers }}
            - name: {{ include "ibkr-gateway.fullname" $dot }}-{{ .name }}-config
              mountPath: {{ .directory | default "/home/trader/app" }}/{{ .config | default "config.yaml" }}
              subPath: {{ .config | default "config.yaml" }}
            {{- end }}
            {{- with .Values.volumes.mounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "ibkr-gateway.fullname" . }}-config
          secret:
            secretName: {{ .Values.config.credentials | default "credentials" }}
            items:
              - key: config.ini
                path: config.ini
        {{- range .Values.config.workers }}
        - name: {{ include "ibkr-gateway.fullname" $dot }}-{{ .name }}-config
          secret:
            secretName: {{ $dot.Values.config.workers_secret | default "workers" }}
        {{- end }}
        - name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
          configMap:
            name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
        - name: {{ include "ibkr-gateway.fullname" . }}-supervisord
          configMap:
            name: {{ include "ibkr-gateway.fullname" . }}-supervisord
        {{- with .Values.volumes.extra }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
