apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: socket
      protocol: TCP
      name: socket
  selector:
    {{- include "ibkr-gateway.selectorLabels" . | nindent 4 }}
