debug = false
port = 6041
logLevel = "info"

[cors]
allowAllOrigins = true

[pool]
maxConnect = 1000
maxIdle = 1000
idleTimeout = "1h"

[ssl]
enable = false

[log]
path = "/var/log/taos"
rotationCount = 30
rotationTime = "1h"
rotationSize = "1GB"

[opentsdb]
enable = false

[influxdb]
enable = false

[statsd]
enable = false

[collectd]
enable = false

[opentsdb_telnet]
enable = false

[node_exporter]
enable = false