apiVersion: v2
appVersion: v0.2.1
description: A Helm chart Microservice for Kubernetes.
name: microservice
version: 0.4.8
home: https://github.com/hartza-capital/helm-charts
keywords:
  - hartza-capital
  - microservice
  - fluxcd
  - prometheus
  - aws
maintainers:
  - name: perriea
    email: aperrier@hartza.capital
