apiVersion: v2
appVersion: v0.2.1
description: A Helm chart Microservice for Kubernetes.
name: microservice
version: 0.1.9
home: https://github.com/arktos-fund/helm-charts
keywords:
  - arktos-fund
  - microservice
maintainers:
  - name: perriea