# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/quotes-strategies

  ingress:
    enabled: false

  config:
    logger:
      format: fmt
      level: warn
    timeout: 10s
    data:
      services:
        companies:
          hostname: companies-microservice.companies
          port: 11000
          timeout: 3s
        quotes:
          hostname: quotes-microservice.quotes
          port: 11000
          timeout: 6s

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false

mongodb:
  enabled: false