# Default values for microservice.

mode: microservice
replicaCount: 1

image:
  repository: rg.nl-ams.scw.cloud/arktos-venture/instruments
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecret: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
  # downscaler/uptime: "Mon-Mon 00:00-12:00 UTC"

podSecurityContext: {}
  # fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe: {}
  # exec:
  #   command: ["/bin/grpc_health_probe", "-addr=:5000"]
  # initialDelaySeconds: 5

readinessProbe: {}
  # exec:
  #   command: ["/bin/grpc_health_probe", "-addr=:5000"]
  # initialDelaySeconds: 5

service:
  type: ClusterIP
  ports:
    http: 8000
    grpc: 11000

# Upstream: https://docs.solo.io/gloo-edge/latest/introduction/architecture/concepts/
# Routes: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/route_table.proto.sk/#routetable
upstream:
  enabled: false
  useHttp2: false
  loadBalancerConfig: {}
  healthChecks:
    enabled: false
    interval: 10s
    timeout: 5s
  rest:
    swagger: indexes.v1.Indexes
    extra: {}
  routes:
    - name: indexes
      path: /v1/indexes
      type: prefix
      methods:
        - GET
      headers:
        - name: "Content-Type"
          value: "application/json"
        - name: "Autorization"
        - name: "X-Account"
      options:
        prefixRewrite: /v1/indexes
        retries:
          numRetries: 3
          perTryTimeout: 5s
          retryOn: connect-failure
        cors:
          allowOrigin:
            - console.arktos.fund
          allowMethods:
            - GET
          allowHeaders:
            - Content-Type
            - Autorization
            - X-Account

env: []
  # - name: TSDB
  #   value: "INSTRUMENTS"
  # - name: API_DEBUG
  #   value: {{ .Values.secrets.debug }}
  # - name: API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: eod-api
  #       key: value

volumes: []
  # - name: nats
  #   secret:
  #     secretName: natscred

fluxcd:
  enabled: true
  interval: 30m
  # semver: 2.0.x

config:
  nats: false
  secret: {}
    # name: "config"
    # key: "microservice"

  # Create new secret
  logger:
    format: fmt
    level: info
  timeout: 3s
  data: {}
    # redis:
    #   hostname: redis
    #   port: 6379
    #   database: 8
    #   timeout: 1.5s
    # postgres:
    #   debug: false
    #   hostname: ext-postgres-data
    #   port: 5432
    #   database: eod
    #   schema: accounts
    #   username: user_rw_eod
    #   password: example
    #   ssl: "disable"
    #   timeout: 3s
    # services:
    #   companies:
    #     hostname: company
    #     port: 11000
    #     timeout: 3s

metrics:
  enabled: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  annotations: {}
    # downscaler/uptime: "Mon-Mon 00:00-12:00 UTC"
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 65

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
  k8s.scaleway.com/pool-name: default

tolerations: []

affinity: {}