# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/quotes

  ingress:
    enabled: false
    hosts:
      - host: api.arktos-consulting.cloud
        paths:
          - path: /grpc/v1/quotes
            pathType: ImplementationSpecific
      - host: api.arktos-consulting.cloud
        paths:
          - path: /v1/quotes
            pathType: ImplementationSpecific

  config:
    logger:
      format: fmt
      level: warn
    timeout: 10s
    data:
      postgres:
        hostname: ext-postgres-data
        port: 5432
        debug: false
        database: eod
        schema: company_quotes
        username: user_ro_eod
        password: example
        ssl: "disable"
        timeout: 3s
      services:
        companies:
          hostname: companies-microservice.companies
          port: 11000
          timeout: 3s

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false
