# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/account-orders

  config:
    secret: "account-orders"

  resources:
    limits:
      cpu: 100m
      memory: 72Mi
    requests:
      cpu: 100m
      memory: 72Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false
