# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/accounts

  ingress:
    enabled: false
    hosts:
      - host: api.arktos-consulting.cloud
        paths:
          - path: /grpc/v1/accounts
            pathType: ImplementationSpecific
      - host: api.arktos-consulting.cloud
        paths:
          - path: /v1/accounts
            pathType: ImplementationSpecific

  config:
    secret: "accounts"

  resources:
    limits:
      cpu: 100m
      memory: 72Mi
    requests:
      cpu: 100m
      memory: 72Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: true

  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 6.2.6-debian-10-r53
    pullSecrets: []
    debug: false
  
  architecture: replication
  auth:
    enabled: false

  master:
    persistence:
      enabled: false

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/redis-exporter
      tag: 1.31.4-debian-10-r11
      pullPolicy: IfNotPresent
      pullSecrets: []

    resources:
      limits:
        cpu: 10m
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 32Mi
