# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/company-trends

  ingress:
    enabled: false

  config:
    logger:
      format: fmt
      level: warn
    timeout: 10s
    data:
      services:
        companies:
          hostname: companies-microservice.companies
          port: 11000
          timeout: 3s

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false
