# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/account-notifications

  ingress:
    enabled: true
    hosts:
      - host: api.arktos-consulting.cloud
        paths:
          - path: /grpc/v1/account/notifications
            pathType: ImplementationSpecific
      - host: api.arktos-consulting.cloud
        paths:
          - path: /v1/account/notifications
            pathType: ImplementationSpecific

  config:
    logger:
      format: fmt
      level: warn
    timeout: 3s
    data:
      redis:
        hostname: redis-master.database
        port: 6379
        database: 13
        timeout: 1.5s
      postgres:
        hostname: ext-postgres-data
        port: 5432
        debug: false
        database: eod
        schema: accounts
        username: user_rw_eod
        password: example
        ssl: "disable"
        timeout: 3s
      services:
        accounts:
          hostname: accounts
          port: 11000
          timeout: 3s

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false
