# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/companies-external

  ingress:
    enabled: false

  env:
    - name: API_DEBUG
      valueFrom:
        secretKeyRef:
          name: eodhistoricaldata
          key: debug
    - name: EOD_KEY
      valueFrom:
        secretKeyRef:
          name: eodhistoricaldata
          key: token

  volumes:
    - name: eodhistoricaldata
      secret:
        secretName: eodhistoricaldata

  config:
    logger:
      format: fmt
      level: warn
    timeout: 5s
    data:
      redis:
        hostname: redis-master.database
        port: 6379
        database: 11
        timeout: 1.5s
      services:
        exchanges:
          hostname: exchanges-microservice.exchanges
          port: 11000
          timeout: 3s

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false

mongodb:
  enabled: false
