# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/company-dividends

  ingress:
    enabled: true
    hosts:
      - host: api.arktos-consulting.cloud
        paths:
          - path: /grpc/v1/company/dividends
            pathType: ImplementationSpecific
      - host: api.arktos-consulting.cloud
        paths:
          - path: /v1/company/dividends
            pathType: ImplementationSpecific

  config:
    logger:
      format: fmt
      level: warn
    timeout: 3s
    data:
      tdengine:
        hostname: tdengine-adapter.database
        port: 6041
        database: investing_accounts
        username: root
        password: taosdata
        timeout: 3s
      services:
        companies:
          hostname: companies-microservice.companies
          port: 11000
          timeout: 3s

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false

mongodb:
  enabled: false