# Default values for microservice.

app:
  image:
    repository: rg.fr-par.scw.cloud/arktos-venture/company-dividends-external

  ingress:
    enabled: false

  config:
    logger:
      format: fmt
      level: warn
    timeout: 3s

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 25m
      memory: 100Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

redis:
  enabled: false

mongodb:
  enabled: false