global:
  imagePullSecrets: []
  storageClass: ""

serviceAccount:
  create: false

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.10-debian-10-r44
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

auth:
  enabled: false

systemLogVerbosity: 0
initdbScripts: {}

startupProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 30

pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""

persistence:
  enabled: true
  storageClass: ""
  size: 2Gi

arbiter:
  enabled: false

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mongodb-exporter
    tag: 0.11.2-debian-10-r354
    pullSecrets: []

  serviceMonitor:
    enabled: true

  resources:
    limits:
      cpu: 30m
      memory: 56Mi
    requests:
      cpu: 30m
      memory: 56Mi

resources:
  limits:
    cpu: 250m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 128Mi