{{- if .Values.cronjob.enabled }}
{{- $dot := . }}
{{- range $akey, $action := .Values.cronjob.actions }}
{{- range $ckey, $country := $dot.Values.cronjob.countries }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "crons.fullname" $dot }}-{{ $ckey }}
  labels:
    {{- include "workers.labels" $dot | nindent 4 }}
spec:
  schedule: {{ $country | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  startingDeadlineSeconds: {{ $action.startingDeadlineSeconds | default 600 }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: {{ include "workers.fullname" $dot }}
          securityContext:
            {{- toYaml $dot.Values.global.podSecurityContext | nindent 12 }}
          containers:
            - name: app
              securityContext:
                {{- toYaml $dot.Values.global.securityContext | nindent 16 }}
              image: {{ $action.image.repository }}:{{ $action.image.tag }}
              imagePullPolicy: {{ $action.image.pullPolicy }}
              env:
                {{- toYaml $action.environment | nindent 16 }}
              resources:
                {{- toYaml $action.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: "/config.yaml"
                  subPath: config.yaml
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: config
              secret:
                secretName: config
                items:
                  - key: {{ $ckey }}
                    path: config.yaml
          {{- with $dot.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $dot.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $dot.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
{{- end -}}