{{- if .Values.cronjob.enabled }}
{{- $dot := . }}
{{- range .Values.cronjob.actions }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "workers.fullname" $dot }}-{{ .name }}
  labels:
    {{- include "workers.labels" $dot | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  startingDeadlineSeconds: {{ .startingDeadlineSeconds | default 600 }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- if $dot.Values.global.serviceAccount.create -}}
          serviceAccountName: {{ include "workers.serviceAccountName" $dot }}
          {{- end }}
          securityContext:
            {{- toYaml $dot.Values.global.podSecurityContext | nindent 12 }}
          containers:
            - name: app
              securityContext:
                {{- toYaml $dot.Values.global.securityContext | nindent 16 }}
              image: {{ .image.repository }}:{{ .image.tag }}
              imagePullPolicy: {{ .image.pullPolicy }}
              command: 
                - "./go" 
                - "--config config.yaml"
              env:
                {{- toYaml .environment | nindent 16 }}
              resources:
                {{- toYaml .resources | nindent 16 }}
          restartPolicy: Never
          {{- with $dot.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $dot.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $dot.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end -}}