{{- if not .Values.existingUsersSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-userlist
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: {{ include "userlist.txt" . | b64enc }}
{{- end -}}