---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tdengine.fullname" . }}-taoscfg
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
data: 
  taos.cfg: |-
    {{- .Values.taosd.taoscfg | nindent 4 }}
