
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tdengine.fullname" . }}-arbitrator
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app: "arbitrator"
spec:
  replicas: {{ .Values.arbitrator.replicaCount }}
  selector:
    matchLabels:
      {{- include "tdengine.selectorLabels" . | nindent 6 }}
      app: "arbitrator"
  template:
    metadata:
      {{- with .Values.taosd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tdengine.selectorLabels" . | nindent 8 }}
        app: "arbitrator"
    spec:
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: arbitrator
          image: "{{ .Values.global.image.prefix }}-arbitrator:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- with .Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: tcp6042
              containerPort: 6042
              protocol: TCP
          resources:
            {{- toYaml .Values.arbitrator.resources | nindent 12 }}
      {{- with .Values.arbitrator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.arbitrator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.arbitrator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

