apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdengine.fullname" . }}-arbitrator
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app: "arbitrator"
spec:
  type: ClusterIP
  ports:
    - name: tcp6042
      port: 6042
      protocol: TCP
  selector:
    app: "arbitrator"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdengine.fullname" . }}
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app: "taosd"
spec:
  type: {{ .Values.taosd.service.type }}
  ports: {{ range $idx, $val := .Values.taosd.service.ports.tcp }}
    - name: tcp{{- $idx}}
      port: {{ $val }}
      protocol: TCP
    {{- end }}
    {{ range $idx, $val := .Values.taosd.service.ports.udp }}
    - name: udp {{- $idx}}
      port: {{ $val }}
      protocol: UDP
    {{- end }}
  selector:
    {{- include "tdengine.selectorLabels" . | nindent 4 }}
    app: "taosd"
