apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tdengine.fullname" . }}
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app: taosd
spec:
  serviceName: {{ include "tdengine.fullname" . }}
  replicas: {{ .Values.taosd.replicaCount }}
  selector:
    matchLabels:
      {{- include "tdengine.selectorLabels" . | nindent 6 }}
      app: taosd
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.taosd.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tdengine.selectorLabels" . | nindent 8 }}
        app: taosd
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-config
          image: "{{ .Values.global.image.prefix }}-init-config:latest"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- with .Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: {{ include "tdengine.fullname" . }}
            - name: STS_NAME
              value: {{ include "tdengine.fullname" . }}
            - name: STS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TAOS_SERVER_PORT
              value: "6030"
            - name: TAOS_FIRST_EP
              value: '$(STS_NAME)-0.$(SERVICE_NAME).$(STS_NAMESPACE).svc.{{ .Values.global.clusterDomainSuffix | default "cluster.local" }}:$(TAOS_SERVER_PORT)'
            - name: TAOS_FQDN
              value: '$(POD_NAME).$(SERVICE_NAME).$(STS_NAMESPACE).svc.{{ .Values.global.clusterDomainSuffix | default "cluster.local" }}'
            - name: TAOS_ARBITRATOR
              value: {{ include "tdengine.fullname" . }}-arbitrator
          volumeMounts:
            - name: {{ include "tdengine.fullname" . }}-taoscfg
              mountPath: /config
              readOnly: true
            - name: config
              mountPath: "/etc/taos"
              readOnly: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.prefix }}-node:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports: {{ range $idx, $val := .Values.taosd.service.ports.tcp }}
            - name: tcp{{- $idx}}
              containerPort: {{ $val }}
              hostPort: {{ $val }}
              protocol: TCP
            {{- end }}
            {{ range $idx, $val := .Values.taosd.service.ports.udp }}
            - name: udp {{- $idx}}
              containerPort: {{ $val }}
              hostPort: {{ $val }}
              protocol: UDP
            {{- end }}
          env:
            - name: CLUSTER
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: {{ include "tdengine.fullname" . }}
            - name: STS_NAME
              value: {{ include "tdengine.fullname" . }}
            - name: STS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TAOS_SERVER_PORT
              value: "6030"
            - name: TAOS_FIRST_EP
              value: '$(STS_NAME)-0.$(SERVICE_NAME).$(STS_NAMESPACE).svc.{{ .Values.global.clusterDomainSuffix | default "cluster.local" }}:$(TAOS_SERVER_PORT)'
            - name: TAOS_FQDN
              value: '$(POD_NAME).$(SERVICE_NAME).$(STS_NAMESPACE).svc.{{ .Values.global.clusterDomainSuffix | default "cluster.local" }}'
          volumeMounts:
            - name: {{ include "tdengine.fullname" . }}-taosdata
              mountPath: /var/lib/taos
              readOnly: false
            - name: {{ include "tdengine.fullname" . }}-taoslog
              mountPath: /var/log/taos
              readOnly: false
            - name: config
              mountPath: "/etc/taos"
              readOnly: true
          readinessProbe:
            exec:
              command:
              - taos
              - -n
              - startup
              - -h
              - "${POD_NAME}"
            initialDelaySeconds: 5
            timeoutSeconds: 5000
          livenessProbe:
            tcpSocket:
              port: 6030
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- with .Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.taosd.resources | nindent 12 }}
      volumes:
        - name: config
          emptyDir: {}
        - name: {{ include "tdengine.fullname" . }}-taoscfg
          configMap:
            name: {{ include "tdengine.fullname" . }}-taoscfg
      {{- with .Values.taosd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.taosd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.taosd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "tdengine.fullname" . }}-taosdata
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "{{ .Values.taosd.storage.className }}"
        resources:
          requests:
            storage: "{{ .Values.taosd.storage.dataSize }}"
    - metadata:
        name: {{ include "tdengine.fullname" . }}-taoslog
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "{{ .Values.taosd.storage.className }}"
        resources:
          requests:
            storage: "{{ .Values.taosd.storage.logSize }}"
