apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.app.schedule | quote }}
  {{- if .Values.suspend }}
  suspend: {{ .Values.suspend }}
  {{- end }}
  concurrencyPolicy: "Forbid"
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  {{- if .Values.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
          {{- with .Values.app.podAnnotations }}
            {{- toYaml . | nindent 12}}
          {{- end }}
          labels:
            {{- include "worker.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: "Never"
          {{- with .Values.app.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "worker.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.app.podSecurityContext | nindent 12 }}
          containers:
            - name: app
              securityContext:
                {{- toYaml .Values.app.securityContext | nindent 18 }}
              image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.app.image.pullPolicy }}
              {{- with .Values.app.env }}
              env:
                {{- toYaml . | nindent 18 }}
              {{- end }}
              volumeMounts:
                - name: {{ include "worker.fullname" . }}-config
                  mountPath: /config/default.yaml
                  subPath: default.yaml
              resources:
                {{- toYaml .Values.app.resources | nindent 14 }}
          volumes:
            - name: {{ include "worker.fullname" . }}-config
              secret:
                secretName: {{ include "worker.fullname" . }}-config
          {{- with .Values.app.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
