{{- if .Values.app.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worker.serviceAccountName" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
  {{- with .Values.app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
