image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.6-debian-10-r53
  pullSecrets: []
  debug: false
  
architecture: replication
auth:
  enabled: true
  sentinel: false
  existingSecret: ""
  existingSecretPasswordKey: ""

master:
  persistence:
    enabled: false

  resources:
    limits: {}
    requests: {}
  
replica:
  replicaCount: 1
  
  persistence:
    enabled: false
  
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: "80"
    # targetMemory: "80"

    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/redis-exporter
      tag: 1.31.4-debian-10-r11
      pullPolicy: IfNotPresent
      pullSecrets: []

    resources:
      limits:
        cpu: 10m
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 32Mi