# Default values for tdengine.

global:
  image:
    prefix: quay.io/arktos-venture/tdengine
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.3.6.0"

  imagePullSecrets: []
    # - name: ""

  podSecurityContext:
    fsGroup: 10001

  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsUser: 10001
    runAsGroup: 10001
    capabilities:
      drop:
        - ALL

  clusterDomainSuffix: ""

taosd:
  replicaCount: 3

  service:
    type: ClusterIP
    ports:
      tcp: [6030,6031,6032,6033,6034, 6035,6036,6037,6038, 6039, 6040, 6041, 6042, 6043, 6044, 6045, 6060]
      udp: [6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039]

  # Config settings in taos.cfg file.
  #
  # The helm/k8s support will use environment variables for taos.cfg,
  # converting an upper-snake-cased variable like `TAOS_DEBUG_FLAG`,
  # to a camelCase taos config variable `debugFlag`.
  #
  # See the variable list at https://www.taosdata.com/cn/documentation/administrator .
  #
  # Note:
  # 1. firstEp/secondEp: should not be setted here, it's auto generated at scale-up.
  # 2. serverPort: should not be setted, we'll use the default 6030 in many places.
  # 3. fqdn: will be auto generated in kubenetes, user should not care about it.
  # 4. role: currently role is not supported - every node is able to be mnode and vnode.
  #
  # Btw, keep quotes "" around the value like below, even the value will be number or not.
  taoscfg: |
    keepColumnName  1
    http  1
    monitor 1
    enableRecordSql 0
    enableCoreFile  1
    stream  0

  storage:
    className: "scw-bssd"
    dataSize: "10Gi"
    logSize: "2Gi"

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 256Mi

  nodeSelectors: {}
  affinity: {}
  tolerations: {}

arbitrator:
  replicaCount: 1

  resources:
    limits:
      cpu: 20m
      memory: 16Mi
    requests:
      cpu: 20m
      memory: 16Mi

  nodeSelectors: {}
  affinity: {}
  tolerations: {}