# Default values for microservice.

app:
  image:
    repository: rg.nl-ams.scw.cloud/arktos-venture/worker-account-currency-positions
    pullPolicy: IfNotPresent
    tag: "0.0.1"

  imagePullSecrets:
    - name: reg-internal
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001

  env: []

  config:
    logger:
      format: fmt
      level: info
    data:
      tdengine:
        hostname: tdengine-cluster.database
        port: 6041
        database: invest_accounts
        username: root
        password: taosdata
        timeout: 3s
        ssl: false
    broker:
      ibkr:
        account: U7793609
        hostname: ibkr-gateway-0.ibkr-gateway.broker-ibkr-u7793609.svc.cluster.local
        port: 5000
        timeout: 3

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

  nodeSelector:
    k8s.scaleway.com/pool-name: app
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

  tolerations: []

  affinity: {}