{{- if eq .Values.mode "microservice" .Values.upstream  }}
{{- if .Values.upstream.enabled  }}
{{- $fullName := include "microservice.fullname" . -}}
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: {{ $fullName }}
spec:
  useHttp2: {{ .Values.upstream.useHttp2 | default true }}
  {{- with .Values.upstream.loadBalancerConfig }}
  loadBalancerConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.upstream.healthChecks.enabled }}
  healthChecks:
    - grpcHealthCheck:
        serviceName: grpc.health.v1.HealthCheckRequest
      interval: {{ .Values.upstream.healthChecks.interval | default "5s" }}
      healthyThreshold: {{ .Values.upstream.healthChecks.healthyThreshold | default 3 }}
      unhealthyThreshold: {{ .Values.upstream.healthChecks.unhealthyThreshold | default 3 }}
  {{- end }}
  kube:
    selector:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
    serviceName: {{ $fullName }}
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{ .Values.service.ports.http }}
    {{- if .Values.upstream.rest }}
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://{{ $fullName }}.{{ .Release.Namespace }}:{{ .Values.service.ports.http }}/q/service/{{ .Values.upstream.rest.swagger | required "swagger field is required" }}
        {{- with .Values.upstream.rest.extra }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}