{{- if eq .Values.mode "microservice" }}
{{- $fullName := include "microservice.fullname" . -}}
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: {{ $fullName }}
spec:
  discoveryMetadata: {}
  useHttp2: {{ .Values.upstream.useHttp2 | default true }}
  loadBalancerConfig: {}
  kube:
    selector:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
    serviceName: {{ $fullName }}
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{ .Values.service.ports.http }}
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://{{ $fullName }}.{{ .Release.Namespace }}:{{ .Values.service.ports.http }}/q/service/{{ .Values.upstream.rest.swagger | required "swagger field is required" }}
        {{- with .Values.upstream.rest.extra }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
{{- end }}