{{- if eq .Values.mode "microservice" }}
{{- if .Values.upstream.enabled  }}
{{- $fullName := include "microservice.fullname" . -}}
{{- $dot := . -}}
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: {{ $fullName }}
spec:
  useHttp2: {{ .Values.upstream.useHttp2 | default true }}
  {{- with .Values.upstream.loadBalancerConfig }}
  loadBalancerConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.upstream.healthChecks.enabled }}
  healthChecks:
    - grpcHealthCheck:
        serviceName: grpc.health.v1.HealthCheckRequest
      interval: {{ .Values.upstream.healthChecks.interval | default "5s" }}
      healthyThreshold: {{ .Values.upstream.healthChecks.healthyThreshold | default 3 }}
      unhealthyThreshold: {{ .Values.upstream.healthChecks.unhealthyThreshold | default 3 }}
  {{- end }}
  kube:
    selector:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
    serviceName: {{ $fullName }}
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{ .Values.service.ports.http }}
    {{- if .Values.upstream.rest }}
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://{{ $fullName }}.{{ .Release.Namespace }}:{{ .Values.service.ports.http }}/q/service/{{ .Values.upstream.rest.swagger | required "swagger field is required" }}
        {{- with .Values.upstream.rest.extra }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- end }}
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: {{ $fullName }}
spec:
  routes:
  {{- range $k, $v := .Values.upstream.routes }}
    - name: {{ $v.name }}
      {{- with $v.options }}
      options:
        cors:
          {{- toYaml $v.options.cors | nindent 10 }}
        timeout: {{ $v.options.timeout | default "3s" | quote }}
      {{- end }}
      matchers:
        - {{ $v.type }}: {{ $v.path | quote }}
          {{- with $v.methods }}
          methods:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $v.headers }}
          headers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $v.queryParameters }}
          queryParameters:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      routeAction:
        single:
          upstream:
            name: {{ $fullName }}
            namespace: {{ $dot.Release.Namespace }}
  {{- end }}
{{- end }}
{{- end }}