{{- $fullName := include "microservice.fullname" . -}}
{{- $dot := . -}}
{{- range .Values.ingress }}
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: {{ $fullName }}-{{ .name }}
spec:
  {{- with .hostname }}
  hostname: {{ . }}
  {{- end }}
  prefix: {{ .prefix }}
  {{- with .method }}
  method: {{ . }}
  {{- end }}
  service: {{ $fullName }}:{{ $dot.Values.service.ports.http }}
  timeout_ms: {{ .timeout_ms | default "4000"}}
  idle_timeout_ms: {{ .idle_timeout_ms | default "500000" }}
  connect_timeout_ms: {{ .connect_timeout_ms | default "2000" }}
  {{- with .service }}
  docs:
    path: /q/service/{{ . }}
  {{- end }}
{{- end }}