{{- $fullName := include "microservice.fullname" . -}}
{{- $dot := . -}}
{{- if eq .Values.mode "microservice" }}
{{- range .Values.ingress }}
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: {{ $fullName }}-{{ .name }}
spec:
  {{- with .hostname }}
  host: {{ . }}
  {{- end }}
  prefix: {{ .prefix }}
  rewrite: {{ .rewrite | default .prefix }}
  {{- with .method }}
  method: {{ . }}
  {{- end }}
  service: {{ $fullName }}.{{ $dot.Release.Namespace }}:{{ $dot.Values.service.ports.http }}
  timeout_ms: {{ .timeout_ms | default "4000"}}
  idle_timeout_ms: {{ .idle_timeout_ms | default "500000" }}
  connect_timeout_ms: {{ .connect_timeout_ms | default "2000" }}
{{- end }}
{{- end }}