{{- $fullName := include "microservice.fullname" . -}}
{{- $dot := . -}}
{{- if eq .Values.mode "microservice" }}
{{- range .Values.ingress }}
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: {{ $fullName }}-{{ .name }}
spec:
  {{- with .hostname }}
  host: {{ . }}
  {{- end }}
  prefix: {{ required "prefix field is required" .prefix }}
  prefix_regex: {{ .prefix_regex | default true }}
  {{- with .rewrite }}
  rewrite: {{ . | default .prefix }}
  {{- end }}
  {{- with .regex_rewrite }}
  regex_rewrite:
    pattern: {{ .pattern | quote }}
    {{- with .substitution }}
    substitution: {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- with .method }}
  method: {{ . }}
  {{- end }}
  service: {{ $fullName }}.{{ $dot.Release.Namespace }}:{{ $dot.Values.service.ports.http }}
  timeout_ms: {{ .timeout_ms | default "4000"}}
  idle_timeout_ms: {{ .idle_timeout_ms | default "500000" }}
  connect_timeout_ms: {{ .connect_timeout_ms | default "2000" }}
{{- end }}
{{- end }}