{{- $fullName := include "microservice.fullname" . -}}
{{- $dot := . -}}
{{- if eq .Values.mode "microservice" }}
{{- range .Values.ingress }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: {{ $fullName }}-{{ .name }}
spec:
  {{- toYaml .values | nindent 2 }}
  service: {{ $fullName }}.{{ $dot.Release.Namespace }}:8000
{{- end }}
{{- end }}