{{- if not .Values.config.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: microservices
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
data:
  default.yaml: {{ include "default.yaml" . | b64enc }}
{{- end }}