---
# Source: ibkr-gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-ibkr-gateway
  labels:
    helm.sh/chart: ibkr-gateway-0.1.1
    app.kubernetes.io/name: ibkr-gateway
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.12.2g"
    app.kubernetes.io/managed-by: Helm
---
# Source: ibkr-gateway/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ibkr-gateway-vmoptions
  labels:
    helm.sh/chart: ibkr-gateway-0.1.1
    app.kubernetes.io/name: ibkr-gateway
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.12.2g"
    app.kubernetes.io/managed-by: Helm
data:
  ibgateway.vmoptions: |-
    -Xmx1024m
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
    -XX:ParallelGCThreads=20
    -XX:ConcGCThreads=5
    -XX:InitiatingHeapOccupancyPercent=70
    -Dinstaller.uuid=3046c7e3-ffbd-4699-a848-117342ff43ee
    -DvmOptionsPath=/home/trader/Jts/ibgateway/1012/ibgateway.vmoptions
    -Dsun.awt.nopixfmt=true
    -Dsun.java2d.noddraw=true
    -Dswing.boldMetal=false
    -Dsun.locale.formatasdefault=true
---
# Source: ibkr-gateway/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ibkr-gateway-proxy
  labels:
    helm.sh/chart: ibkr-gateway-0.1.1
    app.kubernetes.io/name: ibkr-gateway
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.12.2g"
    app.kubernetes.io/managed-by: Helm
data:
  proxy.yaml: |-
    logOptions:
      level: info
      format: json
    socket:
      listen:
        protocol: tcp4
        address: 0.0.0.0:5000
      destination: 
        protocol: tcp6
        address: localhost:4001
      timeout: 3s
    health:
      listen: 0.0.0.0:3000
      timeout: 3s
---
# Source: ibkr-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-ibkr-gateway
  labels:
    helm.sh/chart: ibkr-gateway-0.1.1
    app.kubernetes.io/name: ibkr-gateway
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "10.12.2g"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: ibkr-gateway
      app.kubernetes.io/instance: grafana
  template:
    metadata:
      annotations:
        checksum/gateway: 88228cb8dd59a25351209c26041054a351b995dfce9da7ef0f45bb7432a22ba0
      labels:
        app.kubernetes.io/name: ibkr-gateway
        app.kubernetes.io/instance: grafana
    spec:
      imagePullSecrets:
        - name: reg-internal
      securityContext:
        fsGroup: 10001
      containers:
        - name: gateway
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
          image: "quay.io/arktos-venture/ibkr-gateway:10.12.2h"
          imagePullPolicy: IfNotPresent
          env:
            - name: VNC_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: vnc-credentials
          ports:
            - name: vnc
              containerPort: 6080
              protocol: TCP
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: socket
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 500
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: grafana-ibkr-gateway-config
              mountPath: /opt/ibc/config.ini
              subPath: config.ini
            - name: grafana-ibkr-gateway-vmoptions
              mountPath: /home/trader/Jts/ibgateway/1012/ibgateway.vmoptions
              subPath: ibgateway.vmoptions
            - name: grafana-ibkr-gateway-proxy
              mountPath: /home/trader/proxy.yaml
              subPath: proxy.yaml
          resources:
            limits:
              cpu: 400m
              memory: 1100Mi
            requests:
              cpu: 350m
              memory: 1024Mi
        - name: data-worker-config
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
          image: "rg.nl-ams.scw.cloud/arktos-venture/ibkr-worker:0.0.1"
          imagePullPolicy: 
          volumeMounts:
            - mountPath: /home/noroot/config.yaml
              name: data-worker-config
              subPath: config.yaml
          resources:
            - mountPath: /home/noroot/config.yaml
              name: data-worker-config
              subPath: config.yaml
      volumes:
        - name: grafana-ibkr-gateway-config
          secret:
            secretName: ibkr-credentials
        - name: grafana-ibkr-gateway-vmoptions
          configMap:
            name: grafana-ibkr-gateway-vmoptions
        - name: grafana-ibkr-gateway-proxy
          configMap:
            name: grafana-ibkr-gateway-proxy
        - name: data-worker-config
          secret:
            secretName: data-worker-config
      nodeSelector:
        k8s.scaleway.com/pool-name: app
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
