# Default values for ibkr-gateway.

replicaCount: 1

image:
  repository: perriea/gateway
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  - name: TWS_MAJOR_VRSN
    value: "1012"

config: "ibkr-credentials"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 300m
    memory: 1100Mi
  requests:
    cpu: 300m
    memory: 728Mi

nodeSelector: {}

tolerations: []

affinity: {}
