# Default values for ibkr-gateway.

replicaCount: 1

image:
  repository: perriea/gateway
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  - name: TWS_MAJOR_VRSN
    value: "1012"

config: "ibkr-credentials"

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 300m
    memory: 1100Mi
  requests:
    cpu: 300m
    memory: 728Mi

nodeSelector:
  k8s.scaleway.com/pool-name: app
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux

tolerations: []

affinity: {}
