image:
  repository: quay.io/arktos-venture/ibkr-gateway
  tag: "10.12.2g"

jvm:
  Xmx: "1024"
  XX:
    ConcGCThreads: 5
    InitiatingHeapOccupancyPercent: 70
    ParallelGCThreads: 20
    MaxGCPauseMillis: 200
  installer:
    uuid: "3046c7e3-ffbd-4699-a848-117342ff43ee"

resources:
  limits:
    cpu: 450m
    memory: 1100Mi
  requests:
    cpu: 350m
    memory: 1024Mi