# -- nameOverride is an optional string to substitute for the full names of resources
nameOverride: ""
# -- fullnameOverride is an optional string to substitute for the full names of resources
fullnameOverride: ""

# -- ServiceAccount configuration
serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  create: false
  # -- Annotations to add to the ServiceAccount
  annotations: {}
  # -- The name of the ServiceAccount to use.
  name: ""

# -- Specifies whether a Gateway should be created
image:
  # -- The image repository
  repository: quay.io/hartza-capital/ib-gateway
  # -- The image pull policy
  pullPolicy: IfNotPresent
  # -- The image tag
  tag: ""

# -- imagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this Chart.
imagePullSecrets: []

# -- env is a list of environment variables to set in the container.
env: []
  # - name: VNC_SERVER_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: credentials
  #       key: vnc
  # - name: AWS_ROLE_ARN
  #   value: "arn:aws:iam::111122223333:role/s3-writer"
  # - name: AWS_WEB_IDENTITY_TOKEN_FILE
  #   value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"

# -- debug enables debug mode
debug: false
# -- config is a list of parameters to pass to the gateway
config: 
  # credentials: config.ini key
  credentials: "credentials"
  # workers_secret: config.yaml key
  workers_secret: "workers"
  workers: []
    # - name: worker1
    #   command: "python3 main.py config.yaml"
    #   directory: /home/trader/app
    #   config: config.yaml
    #   startretries: 20
    # - name: worker2
    #   command: "python3 main.py config.yaml"
    #   directory: /home/trader/app2
    #   config: config.yaml
    #   startretries: 20
  live: true

# -- annotations is an optional list of annotations to add to the object metadata
annotations: {}
  # CapacityProvisioned: "0.5vCPU 2GB"
# -- podAnnotations is an optional list of annotations to add to the pod
podAnnotations: {}
  # downscaler/uptime: "Mon-Mon 00:00-12:00 UTC"
  # eks.amazonaws.com/role-arn: arn:aws:iam::012345678912:role/my-example-iam
# -- podSecurityContext is an optional security context to add to the pod
podSecurityContext:
  fsGroup: 10001

# -- securityContext is an optional security context to add to the container
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

# -- jvm is a list of parameters to pass to the JVM
jvm:
  # -- Xmx is the maximum heap size
  Xmx: "2G"
  # -- Xms is the initial heap size
  Xms: "2G"
  # -- Xmn is the minimum heap size
  XX:
    ConcGCThreads: 5
    InitiatingHeapOccupancyPercent: 70
    ParallelGCThreads: 20
    MaxGCPauseMillis: 200
  installer:
    uuid: "3046c7e3-ffbd-4699-a848-117342ff43ee"

# -- volumes is a list of volumes that can be mounted
volumes:
  extra: []
    # - name: aws-token
    #   projected:
    #     sources:
    #       - serviceAccountToken:
    #           audience: "sts.amazonaws.com"
    #           path: token
  mounts: []
    # - name: aws-token
    #   mountPath: "/var/run/secrets/eks.amazonaws.com/serviceaccount/"

# -- resources is an optional list of resources to set for the container
resources:
  limits:
    cpu: 300m
    memory: 2100Mi
  requests:
    cpu: 300m
    memory: 2100Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
