# Default values for ibkr-gateway.

replicaCount: 1

image:
  repository: quay.io/arktos-venture/ibkr-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  - name: VNC_SERVER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: vnc-credentials
        key: password

debug: false
config: 
  IbkrCredentials: "ibkr-credentials"
  trading: "live"

worker:
  logger:
    format: fmt
    level: info
  data:
    redis:
      hostname: redis-master.database
      port: 6379
      database: 7
      read_timeout: 0.2s
      write_timeout: 0.2s
    mongodb:
      hostname: mongodb.database
      port: 27017
      database: companies
      read_timeout: 2s
      write_timeout: 2s
    tdengine:
      hostname: tdengine-cluster.database
      port: 6041
      database: invest_accounts
      username: root
      password: taosdata
      timeout: 3s
      ssl: false

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  port: 5000

jvm:
  Xmx: "768"
  XX:
    ConcGCThreads: 5
    InitiatingHeapOccupancyPercent: 70
    ParallelGCThreads: 20
    MaxGCPauseMillis: 200
  installer:
    uuid: "3046c7e3-ffbd-4699-a848-117342ff43ee"

resources:
  limits:
    cpu: 300m
    memory: 780Mi
  requests:
    cpu: 300m
    memory: 780Mi

nodeSelector:
  k8s.scaleway.com/pool-name: app
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux

tolerations: []

affinity: {}
