# Default values for ibkr-gateway.

replicaCount: 1

image:
  repository: quay.io/arktos-venture/ibkr-gateway
  pullPolicy: IfNotPresent
  tag: "10.12.2g"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

env: []

config: 
  IbkrCredentials: "ibkr-credentials"
  VncCredentials: "vnc-credentials"
  # live or paper
  trading: "live"

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  port: 5000

jvm:
  Xmx: "1024"
  XX:
    ConcGCThreads: 5
    InitiatingHeapOccupancyPercent: 70
    ParallelGCThreads: 20
    MaxGCPauseMillis: 200
  installer:
    uuid: "3046c7e3-ffbd-4699-a848-117342ff43ee"

resources:
  limits:
    cpu: 300m
    memory: 1100Mi
  requests:
    cpu: 300m
    memory: 728Mi

nodeSelector:
  k8s.scaleway.com/pool-name: app
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux

tolerations: []

affinity: {}
