# Default values for ibkr-gateway.

serviceAccount:
  create: true
  annotations: {}
  name: ""

gateway:
  image:
    repository: quay.io/arktos-venture/ibkr-gateway
    pullPolicy: IfNotPresent
    tag: "10.12.2h"

  imagePullSecrets:
  - name: reg-internal
  nameOverride: ""
  fullnameOverride: ""

  env:
    - name: VNC_SERVER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: vnc-credentials
          key: password

  debug: false
  config: 
    IbkrCredentials: "ibkr-credentials"
    trading: "live"

  podAnnotations: {}
  podSecurityContext:
    fsGroup: 10001

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 10001

  jvm:
    Xmx: "1024"
    XX:
      ConcGCThreads: 5
      InitiatingHeapOccupancyPercent: 70
      ParallelGCThreads: 20
      MaxGCPauseMillis: 200
    installer:
      uuid: "3046c7e3-ffbd-4699-a848-117342ff43ee"

  resources:
    limits:
      cpu: 400m
      memory: 1030Mi
    requests:
      cpu: 350m
      memory: 770Mi

sidecars:
  volumes:
    - name: ibkr-worker-config
      secret:
        secretName: ibkr-worker-config

  containers:
    - name: positions-worker
      image: "rg.nl-ams.scw.cloud/arktos-venture/ibkr-positions-worker:0.0.1"
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 10001
      volumeMounts:
        - name: ibkr-worker-config
          mountPath: /home/noroot/config.yaml
          subPath: config.yaml
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi
    - name: companies-worker
      image: "rg.nl-ams.scw.cloud/arktos-venture/ibkr-companies-worker:0.0.1"
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 10001
      volumeMounts:
        - name: ibkr-worker-config
          mountPath: /home/noroot/config.yaml
          subPath: config.yaml
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 64Mi

nodeSelector:
  k8s.scaleway.com/pool-name: app
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux

tolerations: []

affinity: {}
